export const NAVDRAWER = 'nav-drawer-icon.svg'
export const GITHUB = 'github-icon.svg'
export const PINNED = 'pinned.svg'
export const HEART = 'heart.svg'
export const REPOST = 'repost.svg'
export const COMMENTS = 'comments.svg'
export const LINK = 'link.svg'
export const EYE = 'eye.svg'
